### PR TITLE
Improve Dockerfile and README

### LINKED ISSUE #63: The Dockerfile can be improved
## Expected Behavior

The Docker image should be as small as possible and run with an unprivileged user.

## Current Behavior

The Docker image is sub-optimal.

## Possible Solution

Improve the Docker image (PR coming up).

## Context

Docker users should expect the best/smallest possible image.

## Your Environment

- Library Version used: latest from master
- Node.js version (e.g. Node.js 5.4): 12
- Operating System and version (desktop or mobile): GNU+Linux with Docker 19.03.5-ce.

### PR DESCRIPTION
**Pull request by NicolasCARPi**
## Description

* Use node image instead of default alpine image
* Add a .dockerignore file to avoid sending everything to the docker
  daemon as it's not needed
* Use node user instead of root
* Use a more complete LABEL instruction
* Install prod only packages with npm
* Don't write 1.0 in docker build as it's not true
* Move --no-cache docker build option earlier in the command as the
  manual suggests
* Add --rm flag so container is deleted after the run instead of lying
  around dead, never to be used again
* Add syntax highlighting in code blocks on README
* Remove whitespaces from README

This set of changes reduces the Docker image size by 30 Mb.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Related Issue

Fix #63 

## Motivation and Context

Using specialized docker image is always better than to install node on a normal image. Using the unprivileged node user is better than using root user. Reducing docker image size is also good. Improving the documentation on the usage too.

## How Has This Been Tested?

This was tested by running the Docker commands.

## Checklist:

- [X] I have updated the documentation (if required).
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.
- [X] I added a picture of a cute animal cause it's fun

koala

### CODE REVIEW

**Comment by lirantal** [comment]
What a great idea and well-put Pull Request. Thank you @NicolasCARPi 
P.S. the wombat is great, all of our prayers with them 🙏

**Comment by NicolasCARPi** [comment]
What do you mean "wombat", it's a koala! :koala: :smile:

**Comment by lirantal** [comment]
Them too lol 😆

Look at this gem I found:
```
Koalas are more closely related to kangaroos and wombats, which are both members of Diprotodontia, than bears, which belong to the order Carnivora
```

**Comment by lirantal** [comment]
btw pushed image to docker hub too now

**Comment by NicolasCARPi** [comment]
The docker run line in the README should be modified to have `:latest` instead of `:1.0` at the end. Given that submitting a PR is a quite heavy process, can I let you do this quick edit? :)

**Comment by lirantal** [comment]
Oh yes, good catch!

**Comment by lirantal** [comment]
Fixed

**Comment by NicolasCARPi** [comment]
ok so while you're here and very reactive, the sentence on CONTRIBUTING: `Make sure you the code you're adding` has an extra word ;)

**Comment by lirantal** [comment]
Done!
That template needs a change too, I'll fix it in as well https://github.com/lirantal/create-node-lib

**Pull request merged**
