### PR TITLE
docs(local-usage): added instructions for local installation

### PR DESCRIPTION
**Pull request by travi**
## Related Issue

based on conversation from https://github.com/travi/javascript-scaffolder/issues/24#issuecomment-560164100

happy to tie to an issue that is local to this project if you'd prefer

## Motivation and Context

while this tool is useful as a global install or through `npx`, it can also be useful as a local install in combination with an npm script.

## How Has This Been Tested?

i've wired it into the [verification script](https://github.com/travi-org/matt.travi.org/commit/b665fbf35c7a0d6af0526afdf6a1b58265369b8a) for my personal site

## Screenshots (if appropriate):

https://twitter.com/liran_tal/status/1202339318334930944 :)

## Checklist:

- [x] I have updated the documentation (if required).
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] I added a picture of a cute animal cause it's fun

### CODE REVIEW

**Comment by travi** [comment]
i'm not fully sure that this grouping is the most clear, but seemed like the simplest first stab. happy to iterate if you have other ideas

**Comment by lirantal** [comment]
@travi I think these specifically don't add much to the docs as I assume that anyone whose been using npm would know about npx, or do you feel this isn't the case?

**Comment by travi** [comment]
> I assume that anyone whose been using npm would know about npx

i think that is true, but the reverse did leave some questions in my mind about using it as a local script. with a global install or with npx from the terminal, you use a tool like this interactively and are mostly looking for readable output. with a script that is part of a build, exit code is most important and readable output is secondary. you are exiting non-zero, but i wasnt confident of that until i looked at the source code since the example was suggesting using through npx. 

my goal with this was to highlight that it can be used both from the terminal and as a non-interactive script. i agree that having both may not do a great job at clarifying that. i'm ok leaving as is since i do agree that most that are comfortable with cli tools would at least be aware of what to look for.

**Comment by lirantal** [comment]
Yep, will leave it as-is.
Thanks @travi ❤️

**Pull request closed without merging**
