### PR TITLE
feat(jslib): print library information if --js-lib flag is passed

### PR DESCRIPTION
**Pull request by Cardoso222**
## Description
Show library information when `--js-lib` flag is passed

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Related Issue
refs #6 

## Screenshots (if appropriate):
js-library

## Checklist:

- [ ] I have updated the documentation (if required).
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [ ] I added a picture of a cute animal cause it's fun

### CODE REVIEW

**Comment by lirantal** [comment]
@Cardoso222 thanks for sending this.
Could you merge with latest changes from master? (no need to rebase if that is giving you issues since I'll anyway squash the commits when I merge this back).

**Comment by Cardoso222** [comment]
Updated!

**Comment by lirantal** [comment]
@Cardoso222 do you want to follow this up with another PR that updates the README page with the optional `--js-lib` command line argument? like here: https://github.com/lirantal/is-website-vulnerable/blame/master/README.md#L39

**Pull request merged**
